#!/usr/bin/env bash
#SBATCH --job-name=repeatmasker
#SBATCH --cpus-per-task=32
#SBATCH --mem=100G
#SBATCH --time=240:00:00
#SBATCH --output=%x.%N.%j.out
#SBATCH --error=%x.%N.%j.err

set -euo pipefail

# ============================================================
# RepeatMasker pipeline using the Dfam TETools Docker image
# ============================================================
#
# This script runs RepeatMasker on a genome assembly using
# a custom repeat library.
#
# The script is designed to be generic and reusable.
# To use it, edit the variables in the "USER SETTINGS" section
# below, then submit the script with:
#
#   sbatch run_repeatmasker.sh
#
# Requirements:
#   1. A working SLURM environment.
#   2. Docker installed and available on the compute node.
#   3. A genome assembly FASTA file.
#   4. A repeat library FASTA file.
#
# ============================================================


# ============================================================
# USER SETTINGS
# ============================================================
#
# Edit the variables below before submitting the job.
#
# GENOME_FASTA:
#   Path to the input genome assembly FASTA file.
#
# REPEAT_LIBRARY:
#   Path to the custom repeat library FASTA file.
#   This is usually the consensus repeat library generated by
#   RepeatModeler, EDTA, or another repeat-discovery pipeline.
#
# OUTPUT_DIR:
#   Directory where RepeatMasker output files will be written.
#
# THREADS:
#   Number of CPU threads to use.
#   This should usually match the SLURM --cpus-per-task value.
#
# TETOOLS_IMAGE:
#   Docker image used to run RepeatMasker.
#   The Dfam TETools image includes RepeatMasker and related
#   transposable element annotation tools.
#
# ============================================================

GENOME_FASTA="/path/to/genome.fasta"
REPEAT_LIBRARY="/path/to/repeat_library.fa"
OUTPUT_DIR="/path/to/repeatmasker_output"
THREADS="${SLURM_CPUS_PER_TASK:-32}"
TETOOLS_IMAGE="dfam/tetools:latest"


# ============================================================
# CHECK INPUTS
# ============================================================

if [[ ! -f "${GENOME_FASTA}" ]]; then
    echo "ERROR: Genome FASTA file not found:"
    echo "  ${GENOME_FASTA}"
    echo
    echo "Please edit GENOME_FASTA in the USER SETTINGS section."
    exit 1
fi

if [[ ! -f "${REPEAT_LIBRARY}" ]]; then
    echo "ERROR: Repeat library file not found:"
    echo "  ${REPEAT_LIBRARY}"
    echo
    echo "Please edit REPEAT_LIBRARY in the USER SETTINGS section."
    exit 1
fi

if [[ ! -d "${OUTPUT_DIR}" ]]; then
    echo "Output directory does not exist. Creating:"
    echo "  ${OUTPUT_DIR}"
    mkdir -p "${OUTPUT_DIR}"
fi


# ============================================================
# PRINT RUN INFORMATION
# ============================================================

echo "============================================================"
echo "RepeatMasker pipeline started"
echo "============================================================"
echo "Working directory:"
pwd
echo
echo "Hostname:"
hostname
echo
echo "Start time:"
date
echo
echo "Genome FASTA:"
echo "  ${GENOME_FASTA}"
echo
echo "Repeat library:"
echo "  ${REPEAT_LIBRARY}"
echo
echo "Output directory:"
echo "  ${OUTPUT_DIR}"
echo
echo "Threads:"
echo "  ${THREADS}"
echo
echo "Docker image:"
echo "  ${TETOOLS_IMAGE}"
echo "============================================================"


# ============================================================
# PREPARE PATHS FOR DOCKER
# ============================================================
#
# Docker needs access to the input and output files.
#
# This script mounts:
#   - The directory containing the genome FASTA file
#   - The directory containing the repeat library FASTA file
#   - The output directory
#
# Inside the Docker container, these directories are available as:
#   /genome
#   /library
#   /output
#
# This avoids mounting personal or cluster-specific paths directly
# into the command line and keeps the script reusable.
#
# ============================================================

GENOME_DIR="$(dirname "$(readlink -f "${GENOME_FASTA}")")"
GENOME_FILE="$(basename "${GENOME_FASTA}")"

LIBRARY_DIR="$(dirname "$(readlink -f "${REPEAT_LIBRARY}")")"
LIBRARY_FILE="$(basename "${REPEAT_LIBRARY}")"

OUTPUT_DIR_ABS="$(readlink -f "${OUTPUT_DIR}")"


# ============================================================
# RUN REPEATMASKER
# ============================================================
#
# RepeatMasker options used here:
#
# -a
#   Writes alignments in addition to the standard annotation files.
#
# -gff
#   Produces GFF output.
#
# -s
#   Runs RepeatMasker in slow but more sensitive mode.
#
# -pa
#   Number of parallel search jobs.
#
# -lib
#   Custom repeat library FASTA file.
#
# -dir
#   Output directory for RepeatMasker results.
#
# ============================================================

docker run --rm \
    -v "${GENOME_DIR}":/genome:ro \
    -v "${LIBRARY_DIR}":/library:ro \
    -v "${OUTPUT_DIR_ABS}":/output \
    -w /output \
    "${TETOOLS_IMAGE}" \
    bash -c "
        set -euo pipefail

        echo '--- Running RepeatMasker ---'

        RepeatMasker \
            -a \
            -gff \
            -s \
            -pa '${THREADS}' \
            -lib '/library/${LIBRARY_FILE}' \
            -dir /output \
            '/genome/${GENOME_FILE}'

        echo '--- RepeatMasker pipeline completed ---'
    "


# ============================================================
# FINISH
# ============================================================

echo "============================================================"
echo "RepeatMasker pipeline completed"
echo "End time:"
date
echo "============================================================"
